name = "visitor-tracker"
main = "src/index.ts"
compatibility_date = "2025-09-29"

[[durable_objects.bindings]]
name = "PRESENCE_TRACKER"
class_name = "PresenceTracker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PresenceTracker"]