#!/usr/bin/env python3

"""Sync a Raindrop collection into local link-post artifacts.

The Raindrop item ID is the durable identity. New files receive a readable
title-derived slug, but an existing file is never renamed when its title
changes. Items that disappear from the collection are intentionally left
alone; absence is not enough information to delete a published source URL.

Usage:
    RAINDROP_ACCESS_TOKEN=... python3 scripts/raindrop_links_to_posts.py
    python3 scripts/raindrop_links_to_posts.py --dry-run --limit 5
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import unicodedata
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode, urlsplit
from urllib.request import Request, urlopen
from zoneinfo import ZoneInfo


ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_DIR = ROOT / "src" / "content" / "links"
DEFAULT_COLLECTION_ID = "48340159"
API_BASE_URL = "https://api.raindrop.io/rest/v1"
PAGE_SIZE = 50
LOCAL_TZ = ZoneInfo("America/New_York")
GENERATED_COMMENT = (
    "<!-- Generated by scripts/raindrop_links_to_posts.py. "
    "Edit the bookmark in Raindrop instead. -->"
)

RAINDROP_ID_RE = re.compile(r"^raindropId:\s*(\d+)\s*$", re.MULTILINE)
NON_SLUG_RE = re.compile(r"[^a-z0-9]+")


class RaindropAPIError(RuntimeError):
    """Raised when the Raindrop API cannot be read."""


def slugify(value: str, max_length: int = 80) -> str:
    """Return a readable ASCII URL slug."""
    ascii_value = (
        unicodedata.normalize("NFKD", value)
        .encode("ascii", "ignore")
        .decode("ascii")
        .lower()
        .replace("'", "")
    )
    slug = NON_SLUG_RE.sub("-", ascii_value).strip("-")
    if len(slug) <= max_length:
        return slug
    return slug[:max_length].rstrip("-")


def domain_slug(url: str) -> str:
    hostname = (urlsplit(url).hostname or "link").removeprefix("www.")
    return slugify(hostname, max_length=40) or "link"


def url_fallback_slug(url: str) -> str:
    parsed = urlsplit(url)
    path_parts = [part for part in parsed.path.split("/") if part]
    final_part = path_parts[-1] if path_parts else ""
    value = "-".join(part for part in (parsed.hostname or "link", final_part) if part)
    return slugify(value) or "link"


def parse_timestamp(value: Any, field: str, item_id: int) -> datetime:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"Raindrop {item_id} has no valid {field} timestamp")
    try:
        timestamp = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError as error:
        raise ValueError(
            f"Raindrop {item_id} has an invalid {field} timestamp: {value}"
        ) from error
    if timestamp.tzinfo is None:
        raise ValueError(f"Raindrop {item_id} has a timezone-less {field} timestamp")
    return timestamp


def yaml_string(value: str) -> str:
    """JSON strings are valid YAML strings and avoid another dependency."""
    return json.dumps(value, ensure_ascii=False)


def render_link_post(item: dict[str, Any]) -> str:
    item_id = int(item["_id"])
    title = str(item.get("title") or "").strip() or url_fallback_slug(item["link"])
    target = str(item["link"]).strip()
    created = parse_timestamp(item.get("created"), "created", item_id)
    updated = parse_timestamp(
        item.get("lastUpdate") or item.get("created"), "lastUpdate", item_id
    )
    tags = [str(tag).strip() for tag in item.get("tags") or [] if str(tag).strip()]
    note = str(item.get("note") or "").strip()

    frontmatter = [
        "---",
        f"title: {yaml_string(title)}",
        f"target: {yaml_string(target)}",
        f"createdAt: {created.isoformat()}",
        f"updatedAt: {updated.isoformat()}",
        f"raindropId: {item_id}",
        f"tags: {json.dumps(tags, ensure_ascii=False)}",
        "draft: false",
        "---",
        "",
        GENERATED_COMMENT,
    ]
    if note:
        frontmatter.extend(["", note])
    return "\n".join(frontmatter) + "\n"


def validate_item(item: dict[str, Any]) -> tuple[int, str, datetime]:
    try:
        item_id = int(item["_id"])
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError("Raindrop item has no valid numeric _id") from error

    target = str(item.get("link") or "").strip()
    parsed = urlsplit(target)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        raise ValueError(f"Raindrop {item_id} has an invalid HTTP(S) link: {target}")

    created = parse_timestamp(item.get("created"), "created", item_id)
    return item_id, target, created


def load_existing(output_dir: Path) -> tuple[dict[int, Path], set[Path]]:
    by_id: dict[int, Path] = {}
    occupied: set[Path] = set()
    if not output_dir.exists():
        return by_id, occupied

    for path in output_dir.rglob("*.md"):
        occupied.add(path)
        match = RAINDROP_ID_RE.search(path.read_text(encoding="utf-8"))
        if not match:
            continue
        item_id = int(match.group(1))
        if item_id in by_id:
            raise RuntimeError(
                f"Duplicate raindropId {item_id} in {by_id[item_id]} and {path}"
            )
        by_id[item_id] = path
    return by_id, occupied


def choose_new_path(
    output_dir: Path,
    item: dict[str, Any],
    target: str,
    created: datetime,
    occupied: set[Path],
) -> Path:
    title = str(item.get("title") or "").strip()
    base_slug = slugify(title) if title else url_fallback_slug(target)
    base_slug = base_slug or url_fallback_slug(target)
    local_date = created.astimezone(LOCAL_TZ)
    directory = output_dir / str(local_date.year) / f"{local_date.month:02d}"

    candidate = directory / f"{base_slug}.md"
    if candidate not in occupied and not candidate.exists():
        return candidate

    domain = domain_slug(target)
    candidate = directory / f"{base_slug}-{domain}.md"
    if candidate not in occupied and not candidate.exists():
        return candidate

    suffix = 2
    while True:
        candidate = directory / f"{base_slug}-{domain}-{suffix}.md"
        if candidate not in occupied and not candidate.exists():
            return candidate
        suffix += 1


def materialize_items(
    items: Iterable[dict[str, Any]], output_dir: Path, dry_run: bool = False
) -> dict[str, int]:
    existing_by_id, occupied = load_existing(output_dir)
    counts = {"created": 0, "updated": 0, "unchanged": 0, "skipped": 0}

    valid_items: list[tuple[datetime, int, str, dict[str, Any]]] = []
    for item in items:
        try:
            item_id, target, created = validate_item(item)
        except ValueError as error:
            counts["skipped"] += 1
            print(f"Skipping item: {error}", file=sys.stderr)
            continue
        valid_items.append((created, item_id, target, item))

    # Oldest first makes collision resolution deterministic during an initial import.
    valid_items.sort(key=lambda row: (row[0], row[1]))

    for created, item_id, target, item in valid_items:
        content = render_link_post(item)
        path = existing_by_id.get(item_id)
        action = "updated"

        if path is None:
            path = choose_new_path(output_dir, item, target, created, occupied)
            existing_by_id[item_id] = path
            occupied.add(path)
            action = "created"
        elif path.read_text(encoding="utf-8") == content:
            counts["unchanged"] += 1
            continue

        counts[action] += 1
        relative_path = path.relative_to(ROOT) if path.is_relative_to(ROOT) else path
        if dry_run:
            print(f"[dry-run] Would {action[:-1]} {relative_path}")
            continue

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"{action.capitalize()} {relative_path}")

    return counts


def api_get_json(url: str, token: str) -> dict[str, Any]:
    request = Request(
        url,
        headers={
            "Accept": "application/json",
            "Authorization": f"Bearer {token}",
            "User-Agent": "thought-eddies-raindrop-sync/1.0",
        },
    )
    try:
        with urlopen(request, timeout=30) as response:
            data = json.load(response)
    except HTTPError as error:
        body = error.read().decode("utf-8", errors="replace")
        raise RaindropAPIError(
            f"Raindrop API returned HTTP {error.code}: {body[:500]}"
        ) from error
    except (URLError, TimeoutError, json.JSONDecodeError) as error:
        raise RaindropAPIError(f"Unable to read the Raindrop API: {error}") from error

    if not isinstance(data, dict) or data.get("result") is False:
        raise RaindropAPIError(f"Unexpected Raindrop API response: {data}")
    return data


def fetch_collection(
    token: str, collection_id: str, limit: int | None = None
) -> list[dict[str, Any]]:
    items: list[dict[str, Any]] = []
    page = 0

    while limit is None or len(items) < limit:
        remaining = PAGE_SIZE if limit is None else min(PAGE_SIZE, limit - len(items))
        query = urlencode(
            {
                "sort": "-created",
                "page": page,
                "perpage": remaining,
            }
        )
        url = f"{API_BASE_URL}/raindrops/{collection_id}?{query}"
        data = api_get_json(url, token)
        page_items = data.get("items") or []
        if not isinstance(page_items, list):
            raise RaindropAPIError("Raindrop API response did not contain an items list")

        items.extend(item for item in page_items if isinstance(item, dict))
        print(f"Fetched Raindrop page {page + 1}: {len(page_items)} item(s)")

        if len(page_items) < remaining:
            break
        page += 1

    return items[:limit] if limit is not None else items


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync a Raindrop collection to local link posts"
    )
    parser.add_argument(
        "--dry-run", action="store_true", help="Print changes without writing files"
    )
    parser.add_argument(
        "--limit", type=int, help="Only fetch this many of the newest bookmarks"
    )
    parser.add_argument(
        "--collection-id",
        default=os.environ.get("RAINDROP_COLLECTION_ID", DEFAULT_COLLECTION_ID),
        help=f"Raindrop collection ID (default: {DEFAULT_COLLECTION_ID})",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Artifact directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    args = parser.parse_args()

    if args.limit is not None and args.limit <= 0:
        parser.error("--limit must be greater than zero")

    token = os.environ.get("RAINDROP_ACCESS_TOKEN")
    if not token:
        print(
            "Error: RAINDROP_ACCESS_TOKEN is required. Add a Raindrop personal "
            "test token to .env.",
            file=sys.stderr,
        )
        return 1

    try:
        items = fetch_collection(token, str(args.collection_id), args.limit)
        counts = materialize_items(items, args.output_dir.resolve(), args.dry_run)
    except (RaindropAPIError, RuntimeError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1

    print(
        "Sync complete: "
        + ", ".join(f"{value} {key}" for key, value in counts.items())
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
